server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://m220student:vmffkd495@cluster0.smzmj.mongodb.net/transaction?retryWrites=true&w=majority

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG